image: continuumio/miniconda3:4.12.0


tasks: # before and init tasks are pre-built: https://www.gitpod.io/docs/configure/projects/prebuilds

  - name: OpenBB SDK 
    before: |  
      conda create -n obb python=3.9.6 -y                                        
    init: |
      conda activate obb
      pip install openbb==2.0.0
      pip install "openbb[all]"
    command: conda activate obb


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


vscode:
  extensions:
    - almenon.arepl            
    - quarto.quarto
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter
    - eamodio.gitlens
