tasks: # before and init tasks are pre-built: https://www.gitpod.io/docs/configure/projects/prebuilds

  - name: Miniconda OpenBB SDK 
    before: | 
      mkdir -p /workspace/miniconda3-install-script
      curl -o /workspace/miniconda3-install-script/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh                                 
      bash /workspace/miniconda3-install-script/miniconda.sh -b -u -p /workspace/miniconda3
      eval "$(/workspace/miniconda3/bin/conda shell.bash hook)"
      rm -rf /workspace/miniconda3-install-script
      alias conda=/workspace/miniconda3/bin/conda
    init: |
      conda create -n obb python=3.9.6 -y  
      conda activate obb
      pip install --upgrade pip
      pip install openbb[all]==2.2.0
    command: conda activate obb


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter
