tasks: # before and init tasks are pre-built: https://www.gitpod.io/docs/configure/projects/prebuilds

  - name: OpenBB SDK 
    before: | 
      mkdir -p ~/miniconda3
      curl -o ~/miniconda3/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
      bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
      rm -rf ~/miniconda3/miniconda.sh
      ~/miniconda3/bin/conda init bash
      ~/miniconda3/bin/conda init zsh                                    
    init: |
      conda create -n obb python=3.9.6 -y   
      conda activate obb
      pip install openbb[all]==2.0.0
    command: conda activate obb


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


vscode:
  extensions:
    - almenon.arepl            
    - quarto.quarto
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter
    - eamodio.gitlens
